### ISSUE TITLE
Nested Folders/Storages can't be dumped

### ISSUE THREAD

**Issue by jqlifice** [microsoft/compoundfilereader#11]
I created an Office 2003 File (CFB Office, not XML Office File) and tried to dump the dir-stream within the VBA Storage.
Dumping streams in the root storage and its sub-storages works, going deeper prompts a "stream doesn't exist" error, allthough list returns that specific path.

![image](https://github.com/microsoft/compoundfilereader/assets/64926407/c57345af-a4ed-4439-bcde-d6e872f6222a)

**Comment by timepp** [comment]
Hi @jqlifice , do you mind to remove sensitive information and attach your file here?

**Comment by jqlifice** [comment]
[sampleFile.zip](https://github.com/user-attachments/files/16437388/sampleFile.zip)

Hi @timepp,
I have attached a File containing no sensitive Information, but leading to the same result.
Thanks for Looking into it!

**Comment by timepp** [comment]
Thanks @jqlifice, I've found a bug when returning the nested directory name to callback. It's now fixed, please check with latest code.

**Comment by jqlifice** [comment]
@timepp Thanks for your help, it's working on my end as well now :)
